language: node_js
node_js:
  - "12"
before_install:
  - sudo apt-get install ffmpeg libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
jobs:
  include:
    - stage: test
      script: npm test
cache:
  directories:
    - "node_modules"
